[magazinelib]
title = "MagazineLib.com"
url = "https://magazinelib.com"
entrySelector = "article[class*=type-post]"
# titleSelector = "div > header > h3 > a::text"
titleSelector = "div > header > h3 > a"
# linkSelector = "div > header > h3 > a::attr(href)"
linkSelector = "div > header > h3 > a"
# dateSelector = "div > footer > p > time::attr(datetime)"
dateSelector = "div > footer > p > time"
# dateFormat = "yyyy-MM-dd[T]HH:mm:ss"
# onFail = "stale"
# waitUntil = "networkidle"
waitUntil = "load"

[getcomics_packs]
title = "getcomics.info"
url = "https://torrentgalaxy.mx/profile/TheComicGuy"
entrySelector = "div[data-href*=torrent]"
titleSelector = "a:not([id]).txlight[href*=torrent]"
linkSelector = "a:not([id]).txlight[href*=torrent]"
waitUntil = "load"

[nem43_on_1337]
title = "Nem43 on 1337"
url = "https://1337x.to/Nem43-torrents/1/"
entrySelector = "td[class*=coll-1]"
titleSelector = "a[href*=torrent]"
linkSelector = "a[href*=torrent]"
waitUntil = "load"
