[magazinelib]
title = "MagazineLib.com"
url = "https://magazinelib.com"
entrySelector = "article[class*=type-post]"
titleSelector = "div > header > h3 > a"
linkSelector = "div > header > h3 > a"
dateSelector = "div > footer > p > time"
waitUntil = "load"
# titleSelector = "div > header > h3 > a::text"
# linkSelector = "div > header > h3 > a::attr(href)"
# dateSelector = "div > footer > p > time::attr(datetime)"
# dateFormat = "yyyy-MM-dd[T]HH:mm:ss"
# onFail = "stale"
# waitUntil = "networkidle"

[morningstar_india]
title = "Morningstar India articles"
url = "https://www.morningstar.in/library/archives.aspx"
entrySelector = "div.td.col-xs-12"
titleSelector = "a"
linkSelector = "a"
waitUntil = "load"

[kcrw_todays_top_tune]
title = "KCRW Todays Top Tune"
url = "https://www.kcrw.com/music/shows/todays-top-tune"
entrySelector = "div[class*='episode-Item']"
titleSelector = "h3[itemprop*='headline']"
linkSelector = "a.title-link"
waitUntil = "load"

[rotd_uk]
title = "Record Of The Day UK"
url = "https://www.recordoftheday.com/track-archive"
entrySelector = "div.super-box"
titleSelector = ["h3.title", "p.artist"]
linkSelector = ":has(> .super-box) > a.link-box"
waitUntil = "load"

[radiox_uk]
title = "RadioX UK"
url = "https://www.radiox.co.uk/radio/playlist/"
entrySelector = "div.song__text-content"
titleSelector = ["h3 span.track", "h3 span.artist"]
linkSelector = "a.apple_music_badge"
waitUntil = "load"

